FROM alpine
RUN apk update && apk upgrade && apk add --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip && pip3 install --upgrade pip
RUN echo "http://dl-8.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk --no-cache --update-cache add gcc gfortran build-base wget freetype-dev libpng-dev openblas-dev libffi-dev
RUN apk add --no-cache \
        libressl-dev \
        musl-dev && \
    pip3 install --no-cache-dir cryptography && \
    apk del \
        libressl-dev \
        musl-dev \
        libffi-dev
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip3 install --no-cache --upgrade pip setuptools
COPY ./requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# install train container library
COPY ./train_lib /tmp/train-container-library/train_lib
COPY ./setup.py /tmp/train-container-library/setup.py
COPY ./README.md /tmp/train-container-library/README.md
RUN pip3 install --no-cache-dir /tmp/train-container-library/
