FROM python:3.8-slim
MAINTAINER michael.graf@uni-tuebingen.de

COPY ./requirements.txt /tmp/requirements.txt
RUN apt-get update -yqq && \
    apt-get dist-upgrade -yqq && \
    COPY ./requirements.txt /tmp/requirements.txt
# install train container library
COPY ./train_lib /tmp/train-container-library/train_lib
COPY ./setup.py /tmp/train-container-library/setup.py
COPY ./README.md /tmp/train-container-library/README.md
RUN pip install --no-cache-dir /tmp/train-container-library/

ENTRYPOINT ["sh", "/opt/entrypoint.sh"]